testsite/urls.py
# Copyright (c) 2017, DjaoDjin inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
# TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy
from django.views.generic import TemplateView
from saas.views import OrganizationRedirectView, UserRedirectView
from saas.views.plans import CartPlanListView
from urldecorators import include, url

from testsite.views.app import AppView
from testsite.views.organization import OrganizationListView, UserProfileView
from testsite.views.registration import PersonalRegistrationView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

def url_prefixed(regex, view, name=None, decorators=None):
    """
    Returns a urlpattern for public pages.
    """
    return url(r'^' + regex, view, name=name, decorators=decorators)

urlpatterns = [
    # admin doc and panel
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url_prefixed(r'register/$',
        PersonalRegistrationView.as_view(
            success_url=reverse_lazy('home')),
        name='registration_register'),
    url_prefixed(r'^', include('saas.urls.users'),
        decorators=['django.contrib.auth.decorators.login_required']),
    url_prefixed(r'users/(?P<user>[\w.@+-]+)/',
        UserProfileView.as_view(), name='users_profile',
        decorators=['django.contrib.auth.decorators.login_required']),
    url_prefixed(r'users/',
        UserRedirectView.as_view(), name='users_profile_base',
        decorators=['django.contrib.auth.decorators.login_required']),
    url_prefixed(r'', include('django.contrib.auth.urls')),
    url_prefixed(r'saas/$',
        OrganizationListView.as_view(), name='saas_organization_list',
        decorators=['django.contrib.auth.decorators.login_required']),
    url_prefixed(r'$', TemplateView.as_view(template_name='index.html'),
        name='home'),
    url_prefixed(r'billing/cart/',
        login_required(
            OrganizationRedirectView.as_view(
                implicit_create_on_none=True,
                pattern_name='saas_organization_cart'),
            login_url=reverse_lazy('registration_register')),
        name='saas_cart'),
    # saas urls with provider key to implement marketplace.
    url_prefixed(r'api/', include('saas.urls.api.cart')),
    url_prefixed(r'api/', include('saas.urls.api.users'),
        decorators=['saas.decorators.requires_self_provider']),
    url_prefixed(r'api/', include('saas.urls.api.broker'),
        decorators=['saas.decorators.requires_provider_only']),
    # api/charges/:charge/refund must be before api/charges/
    url_prefixed(r'api/',
        include('saas.urls.api.provider.charges'),
        decorators=['saas.decorators.requires_provider_only']),
    url_prefixed(r'api/',
        include('saas.urls.api.provider.billing'),
        decorators=['saas.decorators.requires_direct']),
    url_prefixed(r'api/',
        include('saas.urls.api.provider.profile'),
        decorators=['saas.decorators.requires_direct']),
    url_prefixed(r'api/',
        include('saas.urls.api.provider.metrics'),
        decorators=['saas.decorators.requires_direct']),
    url_prefixed(r'api/', include('saas.urls.api.subscriber'),
        decorators=['saas.decorators.requires_provider']),
    url_prefixed(r'pricing/', CartPlanListView.as_view(),
        name='saas_cart_plan_list'),
    url_prefixed(r'', include('saas.urls.request'),
        decorators=['django.contrib.auth.decorators.login_required']),
    url_prefixed(r'', include('saas.urls.noauth')),
    url_prefixed(r'', include('saas.urls.broker'),
        decorators=['saas.decorators.requires_direct']),
    url_prefixed(r'', include('saas.urls.redirects'),
        decorators=['django.contrib.auth.decorators.login_required']),
    url_prefixed(r'', include('saas.urls.provider'),
        decorators=['saas.decorators.requires_direct']),
    url_prefixed(r'', include('saas.urls.subscriber'),
        decorators=['saas.decorators.requires_provider',
                    'saas.decorators.requires_agreement']),
    url_prefixed(r'app/',
        AppView.as_view(template_name='app.html'), name='app',
        decorators=['django.contrib.auth.decorators.login_required']),
]

saas/models.py
#pylint: disable=too-many-lines

# Copyright (c) 2018, DjaoDjin inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
# TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Implementation Note:
#   The models and managers are declared in the same file to avoid messy
#   import loops.

"""

Subscribers and providers are both instances of ``Organization``. This is done
such that one can be a subscriber to a ``Plan`` for a service hosted on
the broker website as well as itself a provider to other subscribers.
(ex: An organization can provide a CRM tool to subscribers while paying
another app, also hosted on the broker platform, to display usage analytics
of its own product). It is possible to implement
a :doc:`symmetric double-entry bookkeeping ledger<ledger>` by having a single
model ``Organization``.

Typically if you are self-hosting a pure Software-as-a-Service, as opposed to
building a marketplace, you will define a single provider which incidently
is also the the broker (See :doc:`examples<getting-started>`).

A billing profile (credit card and deposit bank account) is represented by
an ``Organization``.
An ``Organization`` subscriber subscribes to services provided by another
``Organization`` provider through a ``Subscription`` to a ``Plan``.
An ``Organization`` represents a billing profile. The ``processor_card_key``
and ``processor_deposit_key`` fields are respectively used when an organization
acts as a subscriber or provider in the subscription relationship.

There are no mechanism provided to authenticate as an ``Organization``.
Instead ``User`` authenticate with the application (through a login page
or an API token). They are then able to access URLs related
to an ``Organization`` based on their relation with that ``Organization``
as implemented by a ``RoleDescription``.
For historical reasons, two roles are often implemented: managers
and contributors (for details see :doc:`Security <security>`).
"""
from __future__ import unicode_literals

import datetime, hashlib, logging, random, re

from dateutil.relativedelta import relativedelta
from django.contrib.auth import get_user_model
from django.core.validators import MaxValueValidator
from django.db import DatabaseError, IntegrityError, models, transaction
from django.db.models import Max, Q, Sum
from django.db.models.query import QuerySet
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.template.defaultfilters import slugify
from django.utils.encoding import python_2_unicode_compatible
from django.utils.http import quote
from django.utils.safestring import mark_safe
from django.utils import six
from django.utils.translation import ugettext_lazy as _
from django_countries.fields import CountryField

from . import humanize, settings, signals
from .backends import get_processor_backend, ProcessorError, CardError
from .utils import (SlugTitleMixin, datetime_or_now,
    extract_full_exception_stack, generate_random_slug, get_role_model)


LOGGER = logging.getLogger(__name__)

#pylint: disable=old-style-class,no-init


class InsufficientFunds(Exception):

    pass


class Price(object):

    def __init__(self, amount, unit):
        assert isinstance(amount, six.integer_types)
        self.amount = amount
        self.unit = unit


class OrganizationManager(models.Manager):

    def create_organization(self, name, creation_time):
        creation_time = datetime.datetime.fromtimestamp(creation_time)
        billing_start = creation_time
        if billing_start.day > 28:
            # Insures that the billing cycle will be on the same day
            # every month.
            if billing_start.month >= 12:
                billing_start = datetime.datetime(billing_start.year + 1,
                    1, 1)
            else:
                billing_start = datetime.datetime(billing_start.year,
                    billing_start.month + 1, 1)
        customer = self.create(created_at=creation_time,
            slug=name, billing_start=billing_start)
        return customer

    def attached(self, user):
        """
        Returns the person ``Organization`` associated to the user or None
        in none can be reliably found.
        """
        if isinstance(user, get_user_model()):
            username = user.username
        elif isinstance(user, six.string_types):
            username = user
        else:
            return None
        queryset = self.filter(slug=username)
        if queryset.exists():
            return queryset.get()
        return None

    def accessible_by(self, user, role_descr=None):
        """
        Returns a QuerySet of Organziation which *user* has an associated
        role with.

        When *user* is a string instead of a ``User`` instance, it will
        be interpreted as a username.
        """
        user_model = get_user_model()
        if not isinstance(user, user_model):
            user = user_model.objects.db_manager(using=self._db).get(
                username=str(user))
        kwargs = {}
        if role_descr:
            if isinstance(role_descr, RoleDescription):
                kwargs = {'role_description': role_descr}
            elif isinstance(role_descr, six.string_types):
                kwargs = {'role_description__slug': str(role_descr)}
            else:
                kwargs = {'role_description__slug__in': [
                    str(descr) for descr in role_descr]}
        roles = get_role_model().objects.db_manager(using=self._db).valid_for(
            user=user, **kwargs)
        return self.filter(pk__in=roles.values('organization')).distinct()

    def find_candidates(self, full_name, user=None):
        """
        Returns a set of organizations based on a fuzzy match of *full_name*
        and the email address of *user*.

        This method is primarly intended in registration pages to help
        a user decides to create a new organization or request access
        to an already existing organization.
        """
        queryset = self.filter(
            Q(slug=slugify(full_name)) | Q(full_name__iexact=full_name))
        if queryset.exists():
            return queryset
        if user:
            email_suffix = user.email.split('@')[-1]
            candidates_from_email = get_role_model().objects.valid_for(
                user__email__iendswith=email_suffix,
                role_description__slug=settings.MANAGER).values(
                    'organization')
            return self.filter(pk__in=candidates_from_email)
        return self.none()

    def providers(self, subscriptions):
        """
        Set of ``Organization`` which provides the plans referenced
        by *subscriptions*.
        """
        if subscriptions:
            # Would be almost straightforward in a single raw SQL query
            # but expressing it for the Django compiler is not easy.
            selectors = set([])
            for subscription in subscriptions:
                selectors |= set([subscription.plan.organization.id])
            return self.filter(pk__in=selectors)
        return self.none()

    def providers_to(self, organization):
        """
        Set of ``Organization`` which provides active services
        to a subscribed *organization*.
        """
        return self.providers(Subscription.objects.valid_for(
            organization=organization))


@python_2_unicode_compatible
class Organization(models.Model):
    """
    The Organization table stores information about who gets
    charged (subscriber) and who gets paid (provider) for using a service.
    A special ``Organization``, named processor, is used to represent
    the backend charge/deposit processor.

    Users can have one of multiple relationships (roles) with an Organization.
    They can either be managers (all permissions) or a custom role defined
    through a ``RoleDescription``.
    """
    #pylint:disable=too-many-instance-attributes

    objects = OrganizationManager()
    slug = models.SlugField(unique=True,
        help_text=_("Unique identifier shown in the URL bar."))

    created_at = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    is_bulk_buyer = models.BooleanField(default=False,
        help_text=mark_safe('Enable GroupBuy (<a href="/docs/#group-billing"'\
' target="_blank">what is it?</a>)'))
    is_provider = models.BooleanField(default=False,
        help_text=_("Can fulfill the provider side of a subscription."))
    full_name = models.CharField(_('Organization name'),
        max_length=60, blank=True)
    # contact by e-mail
    email = models.EmailField(# XXX if we use unique=True here, the project
                              #     wizard must be changed.
    )
    # contact by phone

testsite/views/organization.py
# Copyright (c) 2017, DjaoDjin inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
# TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

from django.views.generic import ListView, TemplateView

from saas.mixins import UserMixin
from saas.models import Organization


class OrganizationListView(ListView):

    model = Organization
    template_name = 'organization_list_index.html'


class UserProfileView(UserMixin, TemplateView):

    template_name = 'accounts/profile.html'

testsite/templates/app.html
{% extends "base.html" %}
{% load static from staticfiles %}

{% block content %}
<div>
    <p>
Welcome to the product!
    </p>
    <p>
If you haven't loaded the test fixtures, you will need to create three
organizations for the demo to work:
<ul>
<li>A payment processor (stripe or razorpay with pk=settings.PROCESSOR_ID)</li>
<li>A broker platform (with slug=settings.PLATFORM)</li>
<li>A subscriber (with slug=request.user)</li>
</ul>
    </p>
    <p>
You will also need to create:
<ul>
<li>A Role such that request.user is a *manager* of subscriber.</li>
<li>a Plan with slug='basic' and advance discount of zero.</li>
</ul>
    </p>
    <div id="upgrades">
        <button id="basic" class="select-item">Upgrade</button>
    </div>
</div>
{% endblock %}

{% block bodyscripts %}
<script type="text/javascript" src="{% static 'js/djaodjin-resources.js' %}"></script>
<script type="text/javascript" src="{% static 'js/djaodjin-saas.js' %}"></script>
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script type="text/javascript">
/** This function is called by RazorPay when the payment was successful.
    We pass the RazorPay payment token to the djaodjin-saas backend
    in order to capture the payment and update subscriptions accordingly.
 */
function paymentSucceeded(response) {
    $.ajax({ type: "POST",
        url: "{{urls.saas_api_checkout}}",
        beforeSend: function(xhr) {
            xhr.setRequestHeader("X-CSRFToken", getMetaCSRFToken());
        },
        data: JSON.stringify({
            "processor_token": response.razorpay_payment_id
        }),
        datatype: "json",
        contentType: "application/json; charset=utf-8",
        success: function(data) {
            $("#upgrades").html("<div id='"+data.processor_key+"'><dl><dt>Status</dt><dd class='charge-status' data-charge-done='The charge succeeded.' data-charge-failed='The charge failed.' data-charge-disputed='The charge was disputed.' data-charge-created='The charge is in progress...'>"+data.state+"</dd></dl><dl><dt>Confirmation Number</dt><dd>"+data.processor_key+"</dd></dl><dl><dt>Amount</dt><dd>"+data.amount+"</dd></dl></div>");
            $("#"+data.processor_key).chargeMonitor({
                initialState: data.state,
                saas_api_charge: "{% url 'saas_api_charges' %}/" + data.processor_key
            });
        },
        error: function(resp) {
            showErrorMessages(resp);
        }
    });

    (response.razorpay_payment_id);
};

jQuery(document).ready(function($) {

    /** When a user clicks on the "Upgrade" button, we add an item into
        her cart, then we retrieve the invoicable cart for that user
        and compute the amount due (including discounts, etc.).
        We pass that total amount to the RazorPay checkout which in turn
        will callback ``paymentSucceeded`` with a payment token
        on a successful charge.
     */
    $(".select-item").click(function (event) {
        var self = $(this);
        event.preventDefault();
        var thisCartItem = new CartItem({
            'plan': self.attr('id'),
            'nb_periods': 1,
            'urls': {'saas_api_cart': "{{urls.saas_api_cart}}"}});
        thisCartItem.add(function(data) {
            $.ajax({
                type: "GET",
                url: "{{urls.saas_api_checkout}}",
                datatype: "json",
                contentType: "application/json; charset=utf-8",
                success: function(data) {
                    var totalAmount = 0;
                    for( var idx = 0; idx < data.length; ++idx ) {
                        for( var jdx = 0; jdx < data[idx].lines.length; ++jdx ) {
                            totalAmount += data[idx].lines[jdx].orig_amount;
                        }
                    }
                    if( totalAmount > 0 ) {
                        var options = {
                          "key": "{{RAZORPAY_PUB_KEY}}",
                          "amount": totalAmount, // 2000 paise = INR 20
                          "name": "Merchant Name",
                          "description": "Purchase Description",
                          "image": "/your_logo.png",
                          "handler": paymentSucceeded,
                          "prefill": {
                            "name": "{{request.user.full_name}}",
                            "email": "{{request.user.email}}"
                          },
                          "notes": {
                            "address": "Hello World"
                          },
                          "theme": {
                            "color": "#F37254"
                          }
                        };
                        var rzp1 = new Razorpay(options);
                        rzp1.open();
                     } else {
                         // All free ...
                         $.ajax({
                             type: "POST",
                             url: "{{urls.saas_api_checkout}}",
                             beforeSend: function(xhr) {
                                 xhr.setRequestHeader("X-CSRFToken", getMetaCSRFToken());
                             },
                             data: JSON.stringify({"processor_token": "dummy"}),
                             datatype: "json",
                             contentType: "application/json; charset=utf-8",
                             success: function(data) {
                                 $("#upgrades").html("<div id='"+data.processor_key+"'><dl><dt>Status</dt><dd class='charge-status' data-charge-done='The charge succeeded.' data-charge-failed='The charge failed.' data-charge-disputed='The charge was disputed.' data-charge-created='The charge is in progress...'>"+data.state+"</dd></dl><dl><dt>Confirmation Number</dt><dd>"+data.processor_key+"</dd></dl><dl><dt>Amount</dt><dd>"+data.amount+"</dd></dl></div>");
                             },
                             error: function(resp) {
                                 showErrorMessages(resp);
                             }
                         });
                     }
                },
                error: function(resp) {
                    showErrorMessages(resp);
                }
            });
        });
    });
});
</script>
{% endblock %}

testsite/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <title>SaaS Testsite</title>
  <script type="text/javascript" src="/static/vendor/js/jquery.js"></script>
  {% if csrf_token %}
  <meta name="csrf-token" content="{{csrf_token}}">
  <script type="text/javascript">
    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
        crossDomain: false, // obviates need for sameOrigin test
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type)) {
                xhr.setRequestHeader("X-CSRFToken", "{{csrf_token}}");
            }
        }
    });
  </script>
  {% endif %}
  {% block localheader %}{% endblock %}
</head>
<body>
  {% block menubar %}
  <div>
  <a href="/">Home</a>
  | <a href="/pricing/">Pricing</a>
  {% if request|is_authenticated %}
  | <a id="authenticated-user" href="{{request|url_profile}}">{{request.user.username}}</a>
  | <a href="/logout/">Sign Out</a>
  {% else %}
  | <a href="/login/">Sign In</a>
  {% endif %}
  </div>
  {% endblock %}
  <div id="messages">
    <div id="messages-content">
      {% for message in request|messages %}
      <div class="alert{% if message.tags %} alert-{{message.tags}}{% endif %}">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <div>{{message|safe}}</div>
      </div>
      {% endfor %}
      {% if form %}
      {% for message in form|messages %}
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <div>{{message}}</div>
      </div>
      {% endfor %}
      {% endif %}
    </div>
  </div>
  {% block content %}{% endblock %}
  {% block footer %}{% endblock %}
</body>
{% block bodyscripts %}{% endblock %}
</html>

testsite/templates/index.html
{% extends "base.html" %}

{% block content %}
<div>
<p>
Welcome to the testsite for djaodjin-saas!
</p>
<p>
This is the ugliest site you will either see. Only the bare minimal markup
necessary to validate the functionality of the project was used.
This way makes it a lot easier to understand what truly matters.
</p>
<p>
Next Sign-in to the admin site (login: donny, password: yoyo) or browse
to the Pricing page and follow the logic a user would go through to sign
up for the service.
</p>
<p>
To test adding managers and contributors, there is 'scott' (pk=3) in
the fixtures.
</p>
</div>
{% endblock %}

testsite/templates/organization_list_index.html
{% extends "base.html" %}

{% block content %}
{% include "saas/organization_list.html" with title="organizations" organizations=object_list %}
{% endblock %}

testsite/templates/paginator.html
<div class="pagination">
  <span class="step-links">
    {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
    {% endif %}

    <span class="current">
      Page {{ page_obj.number }} of {{ paginator.num_pages }}.
    </span>

    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">next</a>
    {% endif %}
  </span>
</div>